//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencia_Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agencia_Viaje()
        {
            this.Contrato_Empleado = new HashSet<Contrato_Empleado>();
            this.Contrato_Agencia = new HashSet<Contrato_Agencia>();
            this.Usuario = new HashSet<Usuario>();
            this.Venta_Pasajes = new HashSet<Venta_Pasajes>();
        }
    
        public int Id_Agencia_Viaje { get; set; }
        public string Razon_Social { get; set; }
        public string Num_Documento { get; set; }
        public string Direccion { get; set; }
        public string Representante_Legal { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Tipo_Documento { get; set; }
        public Nullable<int> Id_Ubigeo { get; set; }
    
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Empleado> Contrato_Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato_Agencia> Contrato_Agencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Pasajes> Venta_Pasajes { get; set; }
    }
}
