//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizacion_Operar
    {
        public int Id_Autorizacion_Operar { get; set; }
        public Nullable<System.DateTime> Fecha_Ini_Operacion { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Operacion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Reg_Avion_ASAP { get; set; }
        public Nullable<int> Id_Permiso_Operacion { get; set; }
    
        public virtual Permiso_Operacion Permiso_Operacion { get; set; }
        public virtual Registro_Avion_ASAP Registro_Avion_ASAP { get; set; }
    }
}
