//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class autorizacionAvionTablaMod
    {
        public string Nomb_Fabricante { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<System.DateTime> Fecha_Fabricacion { get; set; }
        public Nullable<decimal> Peso_Bruto { get; set; }
        public Nullable<decimal> Peso_Neto { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Estado_Propio { get; set; }
        public string Estado { get; set; }
        public int Id_Avion { get; set; }
        public int Id_Reg_Avion_ASAP { get; set; }
        public int Id_Autorizacion_Operar { get; set; }
        public Nullable<int> Id_Permiso_Operacion { get; set; }
    }
}
