//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato_Alquiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato_Alquiler()
        {
            this.Avion = new HashSet<Avion>();
            this.Det_Contrato_Alquiler = new HashSet<Det_Contrato_Alquiler>();
        }
    
        public int Id_Contrato_Alquiler { get; set; }
        public Nullable<System.DateTime> Fecha_Ini_Contrato { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Contrato { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Aerolinea { get; set; }
        public Nullable<int> Id_Provee_Alq_Avion { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avion> Avion { get; set; }
        public virtual Proveedor_Alq_Avion Proveedor_Alq_Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Contrato_Alquiler> Det_Contrato_Alquiler { get; set; }
    }
}
