//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Venta
    {
        public int Id_Det_Venta { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public string Tip_Moneda { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Precio_Descuento { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Estado_Actividad { get; set; }
        public Nullable<int> Id_Venta_Pasaje { get; set; }
        public Nullable<int> Id_Progra_Vuelo { get; set; }
        public Nullable<int> Id_Empleado_Responsable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Programacion_vuelo Programacion_vuelo { get; set; }
        public virtual Venta_Pasajes Venta_Pasajes { get; set; }
    }
}
