//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Ruta_Aerea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Det_Ruta_Aerea()
        {
            this.Permiso_Operacion = new HashSet<Permiso_Operacion>();
            this.Programacion_vuelo = new HashSet<Programacion_vuelo>();
            this.Reg_Cambios_Vuelo = new HashSet<Reg_Cambios_Vuelo>();
        }
    
        public int Id_Det_Ruta_Aerea { get; set; }
        public Nullable<decimal> Kilometraje_Total { get; set; }
        public Nullable<decimal> Tiempo_Total { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Estado_Actividad { get; set; }
        public Nullable<int> Id_Tipo_Ruta { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Ruta_1 { get; set; }
        public Nullable<int> Ruta_2 { get; set; }
        public Nullable<int> Ruta_3 { get; set; }
        public Nullable<int> Ruta_4 { get; set; }
        public Nullable<int> Id_Aerolinea { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_Ruta Tipo_Ruta { get; set; }
        public virtual Ruta_Aerea Ruta_Aerea { get; set; }
        public virtual Ruta_Aerea Ruta_Aerea1 { get; set; }
        public virtual Ruta_Aerea Ruta_Aerea2 { get; set; }
        public virtual Ruta_Aerea Ruta_Aerea3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permiso_Operacion> Permiso_Operacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programacion_vuelo> Programacion_vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reg_Cambios_Vuelo> Reg_Cambios_Vuelo { get; set; }
    }
}
