//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Progra_Tripulacion
    {
        public int Id_Det_Progra_Tripulacion { get; set; }
        public Nullable<int> Cantidad_trip { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Estado_Actividad { get; set; }
        public Nullable<int> Id_Prog_Vuelo { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Rol_Trip { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Programacion_vuelo Programacion_vuelo { get; set; }
        public virtual Rol_Tripulacion Rol_Tripulacion { get; set; }
    }
}
