//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Contrato_Alquiler
    {
        public int Id_Det_Contrato_Alquiler { get; set; }
        public string Num_Placa_Avion { get; set; }
        public Nullable<System.DateTime> Fecha_Ini_Alquiler { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Alquiler { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Estado_Actividad { get; set; }
        public Nullable<int> Id_Contrato_Alquiler { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Contrato_Alquiler Contrato_Alquiler { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
