//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Repuesto
    {
        public int Id_Det_Repuesto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion { get; set; }
        public string Estado_Actividad { get; set; }
        public Nullable<int> Id_Repuesto { get; set; }
        public Nullable<int> Id_Mantenimiento { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
        public virtual Repuestos Repuestos { get; set; }
    }
}
