//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimiento()
        {
            this.Det_Diagnostico = new HashSet<Det_Diagnostico>();
            this.Det_Repuesto = new HashSet<Det_Repuesto>();
            this.Estad_Mant_Asap = new HashSet<Estad_Mant_Asap>();
        }
    
        public int Id_Mantenimiento { get; set; }
        public Nullable<System.DateTime> Fecha_Mant { get; set; }
        public string Estado { get; set; }
        public string Tipo_Mant { get; set; }
        public Nullable<int> Id_Avion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Prove_Mant { get; set; }
    
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Diagnostico> Det_Diagnostico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Repuesto> Det_Repuesto { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estad_Mant_Asap> Estad_Mant_Asap { get; set; }
        public virtual Proveedor_Mantenimiento Proveedor_Mantenimiento { get; set; }
    }
}
