//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisoTablaMod
    {
        public int Id_Permiso_Operacion { get; set; }
        public int Id_Det_Ruta_Aerea { get; set; }
        public string Pais { get; set; }
        public string Departamento { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Ruta_1 { get; set; }
        public Nullable<int> Ruta_2 { get; set; }
        public Nullable<int> Ruta_3 { get; set; }
        public Nullable<int> Ruta_4 { get; set; }
        public string RA1_ORIGEN_AEROPUERTO { get; set; }
        public string RA1_DESTINO_AEROPUERTO { get; set; }
        public string RA2_ORIGEN_AEROPUERTO { get; set; }
        public string RA2_DESTINO_AEROPUERTO { get; set; }
        public string RA3_ORIGEN_AEROPUERTO { get; set; }
        public string RA3_DESTINO_AEROPUERTO { get; set; }
        public string RA4_ORIGEN_AEROPUERTO { get; set; }
        public string RA4_DESTINO_AEROPUERTO { get; set; }
    }
}
