//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso_Operacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permiso_Operacion()
        {
            this.Autorizacion_Operar = new HashSet<Autorizacion_Operar>();
        }
    
        public int Id_Permiso_Operacion { get; set; }
        public Nullable<System.DateTime> Fecha_Solicitud_Operar { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio_Oper { get; set; }
        public Nullable<System.DateTime> Fecha_Fin_Oper { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Det_Ruta_Aerea { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizacion_Operar> Autorizacion_Operar { get; set; }
        public virtual Det_Ruta_Aerea Det_Ruta_Aerea { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
