//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASAPEntities : DbContext
    {
        public ASAPEntities()
            : base("name=ASAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aerolinea> Aerolinea { get; set; }
        public virtual DbSet<Agencia_Viaje> Agencia_Viaje { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Autorizacion_Operar> Autorizacion_Operar { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comprobante_Venta> Comprobante_Venta { get; set; }
        public virtual DbSet<Contrato_Agencia> Contrato_Agencia { get; set; }
        public virtual DbSet<Contrato_Alquiler> Contrato_Alquiler { get; set; }
        public virtual DbSet<Contrato_Empleado> Contrato_Empleado { get; set; }
        public virtual DbSet<Det_Contrato_Alquiler> Det_Contrato_Alquiler { get; set; }
        public virtual DbSet<Det_Diagnostico> Det_Diagnostico { get; set; }
        public virtual DbSet<Det_Progra_Tripulacion> Det_Progra_Tripulacion { get; set; }
        public virtual DbSet<Det_Repuesto> Det_Repuesto { get; set; }
        public virtual DbSet<Det_Ruta_Aerea> Det_Ruta_Aerea { get; set; }
        public virtual DbSet<Det_Servicio> Det_Servicio { get; set; }
        public virtual DbSet<Det_Venta> Det_Venta { get; set; }
        public virtual DbSet<Diagnostico_Tecnico> Diagnostico_Tecnico { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estad_Mant_Asap> Estad_Mant_Asap { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Medio_Compra> Medio_Compra { get; set; }
        public virtual DbSet<Permiso_Operacion> Permiso_Operacion { get; set; }
        public virtual DbSet<Programacion_vuelo> Programacion_vuelo { get; set; }
        public virtual DbSet<Proveedor_Alq_Avion> Proveedor_Alq_Avion { get; set; }
        public virtual DbSet<Proveedor_Mantenimiento> Proveedor_Mantenimiento { get; set; }
        public virtual DbSet<Reg_Cambios_Venta_vuelo> Reg_Cambios_Venta_vuelo { get; set; }
        public virtual DbSet<Reg_Cambios_Vuelo> Reg_Cambios_Vuelo { get; set; }
        public virtual DbSet<Registro_Avion_ASAP> Registro_Avion_ASAP { get; set; }
        public virtual DbSet<Repuestos> Repuestos { get; set; }
        public virtual DbSet<Reserva_Pasaje> Reserva_Pasaje { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Rol_Tripulacion> Rol_Tripulacion { get; set; }
        public virtual DbSet<Ruta_Aerea> Ruta_Aerea { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Tip_Sancion> Tip_Sancion { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
        public virtual DbSet<Tipo_Pago> Tipo_Pago { get; set; }
        public virtual DbSet<Tipo_Ruta> Tipo_Ruta { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
        public virtual DbSet<Urt_Asap> Urt_Asap { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Venta_Pasajes> Venta_Pasajes { get; set; }
        public virtual DbSet<autorizacionAvionTablaMod> autorizacionAvionTablaMod { get; set; }
        public virtual DbSet<autorizacionTablaMod> autorizacionTablaMod { get; set; }
        public virtual DbSet<DETALLE_DE_RUTA> DETALLE_DE_RUTA { get; set; }
        public virtual DbSet<permisoTablaMod> permisoTablaMod { get; set; }
        public virtual DbSet<registroTablaMod> registroTablaMod { get; set; }
    }
}
