//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion_vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programacion_vuelo()
        {
            this.Det_Progra_Tripulacion = new HashSet<Det_Progra_Tripulacion>();
            this.Det_Venta = new HashSet<Det_Venta>();
            this.Reg_Cambios_Venta_vuelo = new HashSet<Reg_Cambios_Venta_vuelo>();
            this.Reg_Cambios_Vuelo = new HashSet<Reg_Cambios_Vuelo>();
            this.Reserva_Pasaje = new HashSet<Reserva_Pasaje>();
        }
    
        public int Id_Progra_Vuelo { get; set; }
        public Nullable<System.DateTime> Fecha_Programacion { get; set; }
        public Nullable<System.DateTime> Fecha_Vuelo { get; set; }
        public Nullable<System.TimeSpan> Hora_Vuelo { get; set; }
        public Nullable<decimal> Tiempo_Vuelo { get; set; }
        public string Estado_Vuelo { get; set; }
        public Nullable<System.DateTime> Fecha_Llegada_vuelo { get; set; }
        public Nullable<System.TimeSpan> Hora_Llegada { get; set; }
        public Nullable<decimal> Precio_Base { get; set; }
        public Nullable<int> Id_Avion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Det_Ruta_Aerea { get; set; }
    
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Progra_Tripulacion> Det_Progra_Tripulacion { get; set; }
        public virtual Det_Ruta_Aerea Det_Ruta_Aerea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Det_Venta> Det_Venta { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reg_Cambios_Venta_vuelo> Reg_Cambios_Venta_vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reg_Cambios_Vuelo> Reg_Cambios_Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva_Pasaje> Reserva_Pasaje { get; set; }
    }
}
