//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Cambios_Venta_vuelo
    {
        public int Id_Cambio_Venta_Vuelo { get; set; }
        public Nullable<System.DateTime> Fecha_Cambio_Venta_vuelo { get; set; }
        public Nullable<int> Id_Comprobante { get; set; }
        public Nullable<int> Id_Progra_Vuelo { get; set; }
    
        public virtual Comprobante_Venta Comprobante_Venta { get; set; }
        public virtual Programacion_vuelo Programacion_vuelo { get; set; }
    }
}
