//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_ASAP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sancion
    {
        public int Id_Sancion { get; set; }
        public string Detalle { get; set; }
        public Nullable<int> Id_Tip_Sancion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tip_Sancion Tip_Sancion { get; set; }
    }
}
